version: '3.3'

services:
  app:
    container_name: ${NODE_CONTAINER_NAME}
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    command: npx nodemon src/app.js
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    depends_on:
      - postgres
    networks:
      - event-management-network
    links:
      - postgres

  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: ${POSTGRES_CONTAINER_IMAGE}
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    volumes:
      - ../docker-data/${NODE_CONTAINER_NAME}/postgres_data:/var/lib/postgresql/data
    networks:
      - event-management-network

networks:
  default:
  event-management-network:
    external: true

volumes:
  app_node_modules: